id: 36550d137ca84784bde70d772e8c411f
initial_creation_type: ocr
source_metadata:
  volumes:
    cf59e39cde6d481f8a3d0d031a38d7dc:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ཐེག་པ་ཆེན་པོའི་ཆོས་བརྒྱ་གསལ་བའི་སྒོའི་བསྟན་བཅོས།
      total_pages: 1517
      volume_number: 77
